### ISSUE TITLE
cms | concept

### ISSUE THREAD

**Issue by 110a** [110a/opizari#6]
3 - ე ენაზე ვამატებდი ინფორმაციას 

<img width="1920" alt="screen shot 2018-06-20 at 17 53 56" src="https://user-images.githubusercontent.com/37026907/41662820-fe213a3a-74b2-11e8-89b2-7ca2adbd1a13.png">

**Comment by GiorgiJangveladze** [comment]
chemtan mushaobs :D ro amoval machvene kargat ra dros xdeba eg errori
